[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake", "yarn"]

[phases.install]
cmds = ["yarn install --network-timeout 300000"]

[phases.build]
cmds = []

[start]
cmd = "node index.js"
